---
title: "Análisis de Accidentes de tránsito en Corea del Sur"
format: html
editor: visual
html: 
  code-fold: true
---

# Introducción

En las distintas sociedades de la actualidad tanto los humanos como los medios de transporte que circulan en las calles han tenido siempre que convivir entre sí. Sin embargo, esta convivencia vial no siempre es la más óptima y segura, esto debido a los distintos tipos de accidentes que ocurren cada día, los cuales pueden dejar personas heridas e incluso muertas. Un fiel reflejo de esta realidad es Corea del Sur, debido a su elevada cantidad de habitantes y el territorio que comprende, el cual es pequeño en comparación. Esta concentración, por tanto, compromete directamente la convivencia y seguridad de los transeúntes y medios de transporte.

A raíz de lo anterior, se utilizará la base de datos de accidentes de tránsito del país surcoreano entre los años 2005 y 2021, con el objetivo de analizar los datos anuales de los distintos tipos de accidentes que existen, el número de ocurrencia de los mismos, además de la respectiva cantidad de heridos y fallecidos en cada uno de ellos.

Este trabajo constará de 4 secciones. En la primera sección plantearán las preguntas a resolver en el proceso de análisis, además de entregar información útil para la contextualización del caso a tratar. En la segunda sección se describirán las variables contenidas en la base de datos y también se explicitarán los distintos tipos de accidentes de tráfico que ocurren dentro de la sociedad surcoreana para tener una mayor claridad en las clasificaciones. En la tercera sección se mostrarán los resultados obtenidos, ordenados anualmente. En una primera instancia, éstos se presentarán de manera gobal, y después se seccionarán según algún tipo de accidente en particular. Por último, se harán conclusiones a partir de la información obtenida en cuanto a las preguntas formuladas, además de reflexionar si estas mismas conclusiones podrían extrapolarse a los contextos de otros países.

# Antecedentes

Como contextualización, en Corea del Sur viven aproximadamente 51.700.000 personas en una superficie de 100.339 kilómetros cuadrados. Esto quiere decir que pueden haber unos 515 habitantes por kilómetro cuadrado conviviendo. Además, el país registra un nivel de urbanización que alcanza el 81%. Esta información nos da indicios de que

Durante el análisis de los datos de los distintos tipos accidentes de tránsito en Corea del Sur, podrían surgir las siguientes preguntas: ¿Cuáles serán los tipos de accidentes que más comúnmente ocurren dentro del país?, ¿de qué manera aumentan, disminuyen o se mantienen estos accidentes con sus respectivas cantidades de muertos y heridos con el paso de los años? Estas preguntas son importantes de responder, ya que podría ayudar a implementar diversas políticas y sistemas de seguridad que puedan prevenir y ,por consiguiente, reducir la cantidad de personas heridas o muertas resultantes de estos incidentes.

# Descripción de variables

En la siguiente tabla se describirán las variables del set de datos a trabajar según el nombre, tipo y descripción de la variable :

| Variable            | Tipo     | Descripción                                                     |
|-----------------|-----------------|--------------------------------------|
| `accidente_tipo_1`  | Caracter | División principal de los tipos de accidentes (4 tipos)         |
| `accidente_tipo_2`  | Caracter | Subdivisiones dentro de los 4 tipos de accidentes principales   |
| `mes`               | Numérica | Mes en que se realizó la observación                            |
| `anio`              | Numérica | Año en que se realizó la observación                            |
| `numero_accidentes` | Numérica | Número de accidentes viales registrados en cierto año y mes     |
| `numero_heridos`    | Numérica | Número de heridos resultantes del accidente en cierto año y mes |
| `numero_muertes`    | Numérica | Número de muertos resultantes del accidente en cierto año y mes |

Ahora, la variable `accidente_tipo_1` cuenta con 4 tipos de accidentes, los cuales a su vez tienen subcategorias. Estas clasificaciones están plasmadas en la siguiente tabla:

| `Auto vs auto`                 | `Auto vs humano`                | `Auto solo`           | `Cruce en vía ferroviaria`                           |
|----------------|----------------|----------------|-------------------------|
| Colisión                       | Cruzando                        | Vuelco                | Cruzando a nivel ferroviario                         |
| Colisión trasera               | Pasando por la calzada          | Colisión              | Irrupción de la barrera ferroviaria                  |
| Colisión trasera en progreso   | Pasando por el borde del camino | Caída                 | Negligencia en la alarma que avisa que viene el tren |
| Colisión trasera al estacionar | Pasando por la vereda           | Desviación del camino | Progreso anterior                                    |
| Otros                          | Otros                           | Otros                 | Otros                                                |

# Resultados

En una primera aproximación al análisis de nuestros datos, se podría estudiar el comportamiento de los 4 tipos de accidentes principales en cuanto a la frecuencia con la que ocurren en el tiempo, tal como se puede observar en la *Figura 1*:

```{r}
#| warning: false
#| message: false
#| echo: false
library(dplyr)
library(ggplot2)
library(readr)
datos_final = read_csv(here::here("datos/datos-final.csv"))
datos_anuales = datos_final %>% filter(mes == "total")
graf_1 = datos_anuales %>%  group_by(accidente_tipo_1, anio,.add = TRUE) %>% 
  summarize(accidentes = sum(numero_accidentes),
            heridos = sum(numero_heridos),
            muertes  = sum(numero_muertes))

graf_1 %>%
  ggplot(aes(anio, accidentes, color = accidente_tipo_1))+
  geom_line(size = 1) +
  scale_y_continuous(breaks = seq(0, 180000, by =15000),
                     labels = c("0","15k","30k","45k","60k","75k","90k","105k","120k","135k","150k","165k","180k")) + 
  labs(title = "Cantidad de accidentes principales a través de los años en unidades
  de miles (k)",
       subtitle = "(2005-2021)",
       x = NULL,
       y = "cantidad de accidentes",
       color = "Tipo de accidente",
       tag = "Figura 1") + 
  scale_color_hue(labels = c("auto vs auto",
                             "auto vs humano",
                             "auto solo",
                             "cruce de vía ferroviaria"))
```

A partir de este gráfico podemos decir que sin duda los incidentes entre autos son los que han producido más cantidad de accidentes a lo largo de los años, con una diferencia bastante más pronunciada respecto de las otras 3 categorías. Sin embargo, a pesar de la divergencia de números entre los grupos, existe un punto en común: estos eventos se han mantenido casi constantes en más o menos medida durante los distintos períodos, sin un descenso significativo en ninguno de ellos.
